### ISSUE TITLE
Дублируются звонки в очередях и маленький кусок кода для улучшения

### ISSUE THREAD

**Issue by Dmitrius7** [dmittr/Asterisk-CDR-Viewer-UserMod#1]
Добрый день!

**Ваша программа просто чудо!!!!**
Я использую FreePBX (asterisk, только с уже готовой web мородой).
Сам asterisk в нем версии 13.32.0

Вчера целый день пробовал разные варианты CDR-Viewer'ов, все давно не обновлялись и работают некорректно! 
Ваш вариант работает отлично, только есть несколько багов.

## Баги:

- Неотвеченные звонки в очереди отмечаются отвеченными;

- Звонки в очереди дублируются;

## Улучшение:

- Русифицировал приложения, теперь вместо dial - Набор номера, queue - Очередь (видел где-то в инете, добавил). Файл во вложении, начало в строке 215 [functions.tar.gz](https://github.com/dmittr/Asterisk-CDR-Viewer-UserMod/files/4664521/functions.tar.gz);

**Все на скриншоте ниже.**

![image](https://user-images.githubusercontent.com/63971386/82602580-fc28aa80-9bb9-11ea-94fd-dfa9fc67f894.png)

Если нужна дополнительная информация или провести тесты, то пишите, сделаю!
Дмитрий
e-mail: ilogy77@gmail.com

Заранее спасибо!

**Comment by dmittr** [comment]
Русификацию добавил. 
Если цель только прослушивание, то можно в конфиге воткнуть параметр 'nofilehide' => 1 в разделе display->main, так скроются все строки для которых нечего проигывать. Звонки в очереди пока нет возможности проверить, но учту на будущее.
