### ISSUE TITLE
Баги и исправления: скобки и добавление перевода

### ISSUE THREAD

**Issue by Dmitrius7** [dmittr/Asterisk-CDR-Viewer-UserMod#2]
Добрый день!

## Еще нашел баги:
На некоторых номерах появляются скобки (исправил)
![image](https://user-images.githubusercontent.com/63971386/82718044-bc8cbc00-9ca8-11ea-9c4f-d64105a992a4.png)

Добавил в русификацию приложений Занято.

## Исправления в файлах в архиве во вложении:

- Строка 511 в index.php ` // Убрал пустые скобки () из колонки кто звонил`
- Строка 240 в index.php перевод Занято.

[Asterisk-CDR-Viewer-UserMod2.tar.gz](https://github.com/dmittr/Asterisk-CDR-Viewer-UserMod/files/4670908/Asterisk-CDR-Viewer-UserMod2.tar.gz)

## По поводу бага с дублированием звонков в очередях
С этим багом я разобрался, теперь ни один звонок не дублируется. Но есть косяки, попробую разобраться. 
Напишу об этом отдельно.

**Comment by dmittr** [comment]
Спасибо, внес правки
